language: python
python:
  - "2.7"
  - "3.5"

before_install:
  - ./build_etcd.sh v2.2.0
  - pip install --upgrade setuptools

# command to install dependencies
install:
  - pip install coveralls
  - pip install coverage
  - python bootstrap.py
  - bin/buildout

# command to run tests
script:
  PATH=$PATH:./etcd/bin coverage run --source=src/etcd --omit="src/etcd/tests/*" bin/test

after_success: coveralls
# Add env var to detect it during build
env: TRAVIS=True
